### ISSUE TITLE
LaTeX Accessibility 

### ISSUE THREAD

**Issue by ayman** [sigchi/Document-Formats#1]
There seem to be some efforts to make [LaTeX properly accessible](https://code.google.com/p/sigchi-latex/wiki/Accessibility).  The class files and templates should reflect this.

**Comment by ayman** [comment]
Turns out this is harder than expected. Efforts are ongoing.

**Comment by matsch-o0** [comment]
**"Add Tags to Document" in Acrobat (v10.1.15) makes document unreadable on iOS 9**

![sigchi-ios9-](https://cloud.githubusercontent.com/assets/599237/9977452/d33fb1ce-5ed6-11e5-93bf-34b77b03e689.jpg)

Steps to reproduce the error:
1. Compile a clean PDF from the proceedings.tex example.
2. "Add Tags to Document" in Acrobat.
3. View on iOS 9 device.
4. Profit!

I don't have an iOS device myself to debug this. The accessible PDF looks fine in iSimulator with iOS 8.2 on my Mac. I know Add Tags introduces an unembedded Times-Roman font. I was able to re-embed the font with Acrobat. Now shows as "TimesNewRoman (Embedded Subset), Type: TrueType (CID)". The problem on iOS 9, however, unfortunately persists.

**Comment by nneonneo** [comment]
@matsch-o0 You probably should file a new issue rather than commenting on this one.

**Comment by ayman** [comment]
Agreed @matsch-o0 please open a new issue.

**Comment by ayman** [comment]
FYI: Some notes on autotagging the document were added to the [Wiki](https://github.com/sigchi/Document-Formats/wiki/Accessibility).
