### ISSUE TITLE
Front page links to Proceedings and Ext Abs format are broked.

### ISSUE THREAD

**Issue by jofish** [sigchi/Document-Formats#10]
CHI uses two different formats for most submissions: CHI Proceedings Format and Extended Abstract Format. Please note that changing the leading, changing the tracking, adding small fonts for references, and other sizing tricks are strictly prohibited.

**Comment by ayman** [comment]
Which page, what links?  Can you please be more specific?

**Comment by ayman** [comment]
Assuming by "Front Page" @jofish meant `README.md` - dead links are empty and should be removed.
