### ISSUE TITLE
Copyright block margins are slightly off in proceedings LaTeX

### ISSUE THREAD

**Issue by mbernst** [sigchi/Document-Formats#101]
<img width="292" alt="alginment" src="https://cloud.githubusercontent.com/assets/249285/23917818/e4717324-08ad-11e7-8efe-2dd5be5eddaf.png">

I'm not enough of a LaTeX wizard to fix this --- it looks to me like the copyright block has a slightly larger left and right margin than the default left column? I tried to align the red lines with the margins of the column.

**Comment by ayman** [comment]
Not sure if this will be addressed as there is a new ACM Global Template which we're gonna migrate to in the near future.
