### ISSUE TITLE
.sty file missing from latest downloadable latex format?

### ISSUE THREAD

**Issue by hci-yeo** [sigchi/Document-Formats#104]
.sty file missing from latest downloadable latex format?

**Comment by alialkhatib** [comment]
[this one?](https://github.com/sigchi/Document-Formats/blob/master/LaTeX/acmcopyright.sty)

**Comment by ayman** [comment]
I'm pretty sure I updated the builds a while back - can you check this page's files: http://sigchi.github.io/Document-Formats/ It's there for me.
