### ISSUE TITLE
Caption style different between Latex and Word

### ISSUE THREAD

**Issue by dalind** [sigchi/Document-Formats#11]
In the word template, captions (also multiline) are centered, in the Latex template only single line captions are centered. 
According to CHI specs, captions should be centered. Also, I think it looks way nicer.

**Comment by ayman** [comment]
Thanks @dalind. Are captions to be centered in both templates or just the proceedings?

**Comment by dalind** [comment]
I _think_ it is just the proceedings, however I don't know for sure.

I fixed it in the Latex template by replacing line 612 in the style with:
`\begin{center}\small\textbf{#1. #2}\par\end{center}     %   THEN set as`

(was:     `\small\textbf{#1. #2}\par\end    %   THEN set as` )

Not a beautiful fix, but works. I think it would be really nice to have center justified captions (justified lines, only last line centered). However, I don't know if this meets the CHI specs. It is also hard to tell, since basically every single paper looks different...

**Comment by jofish** [comment]
To confirm: captions should be centered.

**Comment by ayman** [comment]
@dalind, I think the word is centered though I do agree with you that reading a block of centered text is never optimal.  Ideally, can you send a pull request for your edit?

**Comment by ayman** [comment]
It seems this is legacy in the template, the comment on line 642 of sigchi.cls says:

```
% According to the CHI specifications, captions should be centered.
% This looks kind of bad for multi-line captions, so I only center
% 1-line captions.  
```

The ACM template (not the CHI one) specify this behavior. So I'm going open it up for discussion.

**Comment by dalind** [comment]
@ayman sure, you can send me a pull request for the edit. As I wrote earlier, I think that having the caption text _center justified_ might be a good balance between readability and nice look. 
Anyhow, personally I think centered looks better than simply justified (current template). If centered is in line with the template (according to @jofish), I can fix this and we could discuss about center justified.

**Comment by ayman** [comment]
@jofish and I are discussing how to handle this - we can make the needed
edits when the time comes...but thanks for calling this out.

-a.

**Comment by jofish** [comment]
Ok, here's the revised version. One line captions are centered; longer captions are justified. 
This is implemented in the Word version. I think still needs fixing in the LaTeX.

**Comment by dalind** [comment]
For multi-line captions, is the last line centered or justified?

**Comment by jofish** [comment]
In Word there is no way to center-justify; that is to say, to make the last line centered. That would suggest justifying (or, really, left-aligning, most of the time) the last line. But I don't have a strong opinion on this one.

**Comment by ayman** [comment]
The ACM style is the same here: center one line, justify multiline.  We can investigate how to follow the acm latex to accomplish this if it's possible to do automatically.   If you can check in the corrected word templates (or send them to me) then we'll update the LaTeX accordingly and close the issue.

**Comment by jofish** [comment]
Word updated. Everything is justified in the document, with written instructions to center one-line captions.

**Comment by ayman** [comment]
I don't think you pushed the version of word correctly @jofish.  The EA format seems updated but not the proceedings (varies from the PDF in the repo).  I'm going to address in LaTeX version but the Word proceedings version will need a scrub and update to comply to the various other edits that are happening.
