### ISSUE TITLE
Não consigo executar

### ISSUE THREAD

**Issue by fabriciasantos** [sigchi/Document-Formats#112]
Toda vez que executo, apresenta um erro:
Sorry, but miktex-makemf did not succeed for the following reason: The rtcxr source file could not be found. The log file hopefully contains the information to get MiKTeX going again: .../AppData/Local/MiKTeX/2.9/miktex/log/miktex-makemf.log You may want to visit the MiKTeX project page, if

you need help.

Sorry, but miktex-makepk did not succeed for the following reason: PK font rtcxr could not be created. The log file hopefully contains the information to get MiKTeX going again: .../AppData/Local/MiKTeX/2.9/miktex/log/miktex-makepk.log You may want to visit the MiKTeX project page, if you need help.

Process exited with error(s)

**Comment by cxnvcarol** [comment]
Hello, did you find any workaround to this issue? thanks.
