### ISSUE TITLE
LaTeX template: ACM classification keyword, using old 1998 template

### ISSUE THREAD

**Issue by onovo1** [sigchi/Document-Formats#113]
Hi,

I am using the proceedings template in the LaTeX format. The template includes a section to classify the paper called "ACM classification keywords". However, that section uses the old classification system that does not exist any more. The 1998 template (http://acm.org/about/class/1998/) cannot be found in the ACM website. The new template is the 2012 template, you can find more information from here:
https://www.acm.org/about-acm/class

Unfortunately, the LaTeX template does not work with the 2012 classification. The template should accept a classification similar to the example below:

 \begin{CCSXML}
<ccs2012>
<concept>
<concept_id>10003752.10010124.10010131.10010136</concept_id>
<concept_desc>Theory of computation~Action semantics</concept_desc>
<concept_significance>300</concept_significance>
</concept>
</ccs2012>
\end{CCSXML}

\ccsdesc[300]{Theory of computation~Action semantics}

However, it ignores that classification. 
Any idea on how to fix that?

Thanks!

**Comment by hrosser** [comment]
The issue still exists, but I was able to access the codes for the 1998 classification on the ACM website by searching for 1998 classification specifically.  Here is the link for reference:  https://www.acm.org/publications/computing-classification-system/1998/about

**Comment by onovo1** [comment]
Thank you for the note!

**Comment by philgough** [comment]
Is there any plan to include the modern classification systems in this class? The 1998 classification is pretty dated now.
