### ISSUE TITLE
Referencing a section is impossible

### ISSUE THREAD

**Issue by ToJa92** [sigchi/Document-Formats#12]
I've tried to reference a section which was previously labeled, but no matter what I try (\ref, \autoref, \pageref, etc.) no reference is produced. I'm using ShareLaTeX, which is a web-based LaTeX editor. I've not tried to compile locally.

The entire LaTeX log is [available here](https://gist.github.com/ToJa92/37f3d909eb7490e0aaf9).

Here's a minimal example (which is based on the included `proceedings.tex`):

``` latex
\documentclass{sigchi}

% Load basic packages
\usepackage{balance}  % to better equalize the last page
\usepackage{graphics} % for EPS, load graphicx instead 
\usepackage{txfonts}
\usepackage{times}    % comment if you want LaTeX's default font
\usepackage[pdftex]{hyperref}
\usepackage{color}
\usepackage{textcomp}
\usepackage{booktabs}
\usepackage{ccicons}
\usepackage{todonotes}

% llt: Define a global style for URLs, rather that the default one
\makeatletter
\def\url@leostyle{%
  \@ifundefined{selectfont}{\def\UrlFont{\sf}}{\def\UrlFont{\small\bf\ttfamily}}}
\makeatother
\urlstyle{leo}

% To make various LaTeX processors do the right thing with page size.
\def\pprw{8.5in}
\def\pprh{11in}
\special{papersize=\pprw,\pprh}
\setlength{\paperwidth}{\pprw}
\setlength{\paperheight}{\pprh}
\setlength{\pdfpagewidth}{\pprw}
\setlength{\pdfpageheight}{\pprh}

% Make sure hyperref comes last of your loaded packages, to give it a
% fighting chance of not being over-written, since its job is to
% redefine many LaTeX commands.
\definecolor{linkColor}{RGB}{6,125,233}
\hypersetup{%
  pdftitle={SIGCHI Conference Proceedings Format},
  pdfauthor={LaTeX},
  pdfkeywords={SIGCHI, proceedings, archival format},
  bookmarksnumbered,
  pdfstartview={FitH},
  colorlinks,
  citecolor=black,
  filecolor=black,
  linkcolor=black,
  urlcolor=linkColor,
  breaklinks=true,
}

\begin{document}
\section{Section}
\label{sec:section}
This is a section.
\section{Referencing}
Here's a reference to the previous section: \ref{sec:section}.
\end{document}
```

**Comment by ayman** [comment]
Sections don't have numbers in the CHI format, so I'm not sure what is the expected output in that case, but I suppose `pageref` _should_ work however, it's discouraged as you don't know what page of the proceedings will actually print.  

Refs to other numbered objects should work (equations, lists, etc.).

**Comment by ayman** [comment]
Just to follow up @ToJa92 your example compiles without error in the standard MacTeX package. The `\pageref{}` command works if `\pagenumbering{arabic}` is in the preamble but really this shouldn't be done as page numbers are not known until final publication.

**Comment by debapratimsaha** [comment]
How to refer to Sections in ACM sigchi-ext document class? 

Update: I used \nameref, which outputs the full name of the section. This is not the desired output, its a waste of space.
