### ISSUE TITLE
Orphan headings

### ISSUE THREAD

**Issue by Noleli** [sigchi/Document-Formats#14]
There's a tendency for section headers to get typeset at the bottom of columns or pages in the proceedings format. In the sample, Figures/Captions and Conclusion are examples.

**Comment by henningpohl** [comment]
I ran into this problem a while ago, but got a helpful response on stackexchange: http://tex.stackexchange.com/questions/74262/orphans-when-using-the-sigchi-latex-style.

I fixed this in https://github.com/henningpohl/sigchi-alternative, but it should be straightforward to also incorporate the change into this template.

**Comment by ayman** [comment]
Do you have a pull request?
