### ISSUE TITLE
todonotes throws error

### ISSUE THREAD

**Issue by wbueschel** [sigchi/Document-Formats#19]
Using `\todo` (from the todonotes package) in the latex template does produce the following error in the line where the command is used:
`TeX capacity exceeded, sorry [input stack size=5000].`
I tested this on both Windows and OS X, using MikTex, Tex Live, and MacTex.

**Comment by derric** [comment]
:+1: I have the same problem

**Comment by ayman** [comment]
How are you calling the notes?  Generally you have to specify inline as there is no side page margin:

``` latex
\usepackage{todonotes}
. . .
\todo[inline]{foobar}
```

**Comment by wbueschel** [comment]
Thanks for your quick help! This does indeed make the document compile. Maybe inline should be the default?

**Comment by ayman** [comment]
I'd rather just remove the package as we used it during debugging and really don't want to 'support' it as such.

**Comment by wbueschel** [comment]
Yes, the inline option doesn't look very helpful anyways (uses too much space.) I have defined my own command for todos now. Something like `\definecolor{todo}{rgb}{0,.7,.2}
\newcommand{\todo}[1]{\textcolor{todo}{(TODO: #1)}}` is sufficient, for me at least.

**Comment by ayman** [comment]
Reopening for @floe's pull request/solution #22.

**Comment by ayman** [comment]
Just took this.  Thanks.  I'm wondering if the .tex example or the .cls file should document this else nobody will find it.  Thoughts @floe?

**Comment by floe** [comment]
Good point, I'll prepare a small example for the .tex template.

**Comment by ayman** [comment]
Leave it commented out somewhere in the header as an example. I'll merge
and likely update a bit.

**Comment by ayman** [comment]
`chi_draft` should now allow for this.  We're gonna leave it a bit hidden for now but might add more instructions later in the template or readme.

**Comment by vinhqdang** [comment]
Hello all

I have the same problem today with \todonotes and CHI format. What is a good way to use \todo{} with CHI format? (except _inline_ mode which I already used).

Thanks

**Comment by ayman** [comment]
@vinhqdang did you try the `chi_draft` option?
