### ISSUE TITLE
Default bibliography style is very verbose

### ISSUE THREAD

**Issue by floe** [sigchi/Document-Formats#21]
The default .bst style is now _extremely_ verbose IMHO. Also, it kind of contradicts the instructions, which specify that conference proceedings should be abbreviated as "Proc. XXX 2016", while the style currently always uses the full `booktitle` field. May I suggest to change the default to using "Proc." + `series` instead?

**Comment by ayman** [comment]
The `bst` is pulled from the current official ACM `bst` with minimal edits to match CHI's citation format.  AFAIK, abbreviations are suggested and not mandated.
