### ISSUE TITLE
Latex - Proceedings, ExtAbs : Update table 1 to match Word

### ISSUE THREAD

**Issue by jofish** [sigchi/Document-Formats#27]
Update Table 1 to match word document as per image. I've seen reports that the current table can be confusing, because it looks like it conveys useful information when it's actually just sample text. This new table shows a variety of number formats, includes highlighting and less redundant lines. (And is a shout out to some of our colleagues who have left us.) 
![image](https://cloud.githubusercontent.com/assets/582167/8688459/553b3e6a-2a51-11e5-9a7c-edf6cf187d7e.png)

**Comment by ayman** [comment]
Actually, this table is way more basic than the more sophisticated version: 

![image](https://cloud.githubusercontent.com/assets/1846/9011712/dc037a6a-3763-11e5-9e58-be275c64e8be.png)

I'd like to have the word format (whatever the content) be more sophisticated.   Also, this table is a table referring to the old and new formats...which is actually real data.

**Comment by jofish** [comment]
Disagree on providing real data. Have had a few comments that it was confusing.

Revised version is as "sophisticated" as the old one.

![image](https://cloud.githubusercontent.com/assets/582167/9012946/b9225bea-37b0-11e5-99a7-9e70a637349e.png)

Update LaTeX to match.
