### ISSUE TITLE
Latex - Proceedings and ExtAbs - Add Quotes section

### ISSUE THREAD

**Issue by jofish** [sigchi/Document-Formats#29]
Add section before Language, Style and Content called Quotes thus:

**Quotes**
Quotes should be italicized. Short quotes “_may be placed inline_” (Anab, 22F).
_Longer quotes may be placed in their own paragraph and need not be in quotation marks_. (Ramon, 39M).

**Comment by ayman** [comment]
Would like more info here as to why it's not: 

Short quotes may be italicized if "they are inline" (Anab, 22F) Longer quotes, when placed in their own paragraph need not be in quotation marks. (Ramon, 39M).

The forcing here would lead to people less optimally organizing their paper, so the prescriptive optional advice is the better path.   I'm not sure if an indent is present if it still needs italics...and a paragraph of italics is harder to read.

**Comment by jofish** [comment]
Fair enough.

Changed to 

Quotes may be italicized and “placed inline” (Anab, 22F).
Longer quotes, when placed in their own paragraph, need not be italicized or in quotation marks. (Ramon, 39M). 

Please update LaTex to match.

**Comment by ayman** [comment]
There's the question of where do the periods go.
1. Quotes may be italicized and “placed inline” (Anab, 22F).
2. Quotes may be italicized and “placed inline.” (Anab, 22F)
3. Quotes may be italicized and “placed inline.” (Anab, 22F).

I'm opting for version 1 which follows reference citation.
