### ISSUE TITLE
Latex - Proceedings  - rendering of Nguyễn

### ISSUE THREAD

**Issue by jofish** [sigchi/Document-Formats#30]
Check rendering of 
![image](https://cloud.githubusercontent.com/assets/582167/8688559/740f3fa2-2a52-11e5-8c89-d36c6216af86.png)
as it is currently not coming through correctly:
![image](https://cloud.githubusercontent.com/assets/582167/8688570/93330486-2a52-11e5-9515-852fda6b4dbc.png)

**Comment by ayman** [comment]
Closes with #31.
