### ISSUE TITLE
Latex - ExtAbs - Add advice on extended character set  

### ISSUE THREAD

**Issue by jofish** [sigchi/Document-Formats#31]
Add advice on using extended character set (copy verbiage from Proceedings)

![image](https://cloud.githubusercontent.com/assets/582167/8688590/cc3d092a-2a52-11e5-9dc5-60f775ebb49b.png)

**Comment by ayman** [comment]
LaTeX does this by itself, not sure if it's needed. However the vietnemese might pose some issue as it's a hard case to trap and is done only if needed in tex.  not sure if we want to keep it.
