### ISSUE TITLE
Title gets squashed for manual multi-line (i.e. insert "\\" in title)

### ISSUE THREAD

**Issue by dalind** [sigchi/Document-Formats#40]
When the title breaks to the next line automatically, everything is fine.
If one inserts a "\", the template thinks it is a subtitle and changes the baselineskip.
I think this can be resolved by uncommenting line 775 in sigchi.cls (%baselineskip 20pt   %[jdf] no skip}.

**Comment by ayman** [comment]
Are you trying to manually introduce a break?

**Comment by dalind** [comment]
Yes

**Comment by ayman** [comment]
I think `\\` is line break and not `\`.  Can you verify or provide a code snippet?  Details [here](http://www.personal.ceu.hu/tex/breaking.htm).

**Comment by dalind** [comment]
I added two pictures showing the issue. 
First picture with manual line break \, second picture with automatic break. You can see that the "S" from SIGCHI and the "P" from Proceedings are squeezed together in the first images, whereas everything is fine in the second one.

Might be picky, but we had the issue in a recent paper that the title just looked strange because of the distance between the lines being too small.

Picture 1 (bad title, manual break):
![bad_title](https://cloud.githubusercontent.com/assets/6469238/9248789/1e55110c-41bf-11e5-9011-0d033743b800.png)

Picture 2 (good title, auto break):
![good_title](https://cloud.githubusercontent.com/assets/6469238/9248791/21662cbe-41bf-11e5-87b5-f334383cdfa5.png)

**Comment by dalind** [comment]
(sorry, accidentally closed)

**Comment by ayman** [comment]
interesting...will investigate.
