### ISSUE TITLE
UPDATED date in Word needs to be a static string not a dynamic date

### ISSUE THREAD

**Issue by jofish** [sigchi/Document-Formats#42]
Right now both Word docs start the abstract with 

UPDATED - 24 August 2015

That needs to be a static string, not an auto-updating date. It's very easy to accidentally put in an automatically updating date field -- if you hit return when the yellow window saying 24 August 2015, then it'll be replaced with an automatically updating field. It looks like this got changed (by accident) in the last Word doc update. It needs to get changed back.

**Comment by ayman** [comment]
Why can't it be an autoupdate for the template (I actually set it to be)?  It makes the builds & pdfs be stamped correctly.

**Comment by jofish** [comment]
No, it doesn't. It means that every time someone downloads the template, it says, in essence, This Template Was Last Updated Today. That's a lie. It's confusing and poor user experience. That's why it should be a static string.

**Comment by ayman** [comment]
Is the date string updated on open or on save?  If it's the former then ok to fix.

**Comment by jofish** [comment]
No, it's not ok. It is updated on open. And right now it implies when they open the document that it was updated today. That means it can't be used as a version referrer, which is a really useful tool as we've seen. If you want to put some other version control in the document, that's another question. But the UPDATED - string has been consistently the date of the last update of the template for several years, and should not be broken. This needs to get changed back.

**Comment by ayman** [comment]
Fixed.
