### ISSUE TITLE
Accents in affiliations and author names - öüä

### ISSUE THREAD

**Issue by streuselcake** [sigchi/Document-Formats#46]
Hi all, what is the correct way to use accents with the sigchi class?

**Comment by floe** [comment]
IMHO the most portable way is to use an UTF8-capable editor and uncomment `\usepackage[utf8]{inputenc}` in the template.

**Comment by streuselcake** [comment]
I am sorry, I wanted to ask, what is the correct way to write accents in authors and affiliations...?

**Comment by ayman** [comment]
I believe the Extended Abstract format shows an example.  There's no one correct way and @floe likely has the easiest solution here.
