### ISSUE TITLE
citations with the same author and year append letters to year in LaTeX

### ISSUE THREAD

**Issue by snapdragoness** [sigchi/Document-Formats#48]
When citing two works by the same authors in the same year, the LaTeX template appends letters to the end of the year. Since SIGCHI is not using the `(author, year)` format for citations, it is unclear if this is working as intended.

Screenshot attached.

![screen shot 2015-09-09 at 11 40 36 am](https://cloud.githubusercontent.com/assets/3452924/9769476/a07c99c4-56e7-11e5-8639-0d682a8b4f35.png)

**Comment by ayman** [comment]
This is working as intended (an as per the ACM spec).
