### ISSUE TITLE
Incorrect page references in sections for LaTeX template

### ISSUE THREAD

**Issue by floe** [sigchi/Document-Formats#49]
Just realized that in the auto-generated TOC, all top-level sections will link back to page 1, no matter where the section actually is in the document. [Sub]subsections work correctly, however - see below for a (slightly obfuscated) example. This is with most recent master branch.
![screenshot from 2015-09-14 20 37 41](https://cloud.githubusercontent.com/assets/90756/9858504/67de8616-5b21-11e5-9157-c7dd6518a21d.png)

**Comment by ayman** [comment]
Just asking, did you try a clean make? sometimes `hyperref` gets out of sync.

**Comment by floe** [comment]
Yes, still happens after a rebuild from clean directory. In fact, I've been seeing this in several other papers I'm currently reviewing, hence the bug report.

**Comment by ayman** [comment]
Just asking for context and so i might could reproduce.  And is
pagenumbering on in your doc?
https://github.com/sigchi/Document-Formats/blob/master/LaTeX/proceedings.tex#L16

**Comment by floe** [comment]
Doesn't make a difference, happens with and without page numbering. Enabling `\usepackage[all]{hypcap}` also has no effect.

**Comment by floe** [comment]
Proposed fix in #53.

**Comment by simonrob** [comment]
Proposed #56 as a different approach to fixing this.
