### ISSUE TITLE
problem with crossref

### ISSUE THREAD

**Issue by snapdragoness** [sigchi/Document-Formats#51]
Bibliography items that have a `crossref` to other references do not render correctly: the leading square bracket is missing from the typeset cross-reference (or a trailing close bracket is added). Unclear if this is a bug or just unsupported; it is easy to work around. A `crossref`'ed set of entries follows, as well as a screenshot of the output.

`@incollection{Jorgensen:2013ab,
    Crossref = {Jorgensen:2013aa},
    Pages = {54--104},
    Title = {The Gameworld as Interface}}`

`@book{Jorgensen:2013aa,
    Address = {Cambridge, MA, USA},
    Author = {Kristine J{\o}rgensen},
    Booktitle = {Gameworld Interfaces},
    Publisher = {MIT Press},
    Title = {Gameworld Interfaces},
    Year = {2013}}`

![screen shot 2015-09-16 at 12 17 45 pm 2](https://cloud.githubusercontent.com/assets/3452924/9914004/0af2b268-5c6d-11e5-9b49-0ce5190dead6.png)

**Comment by ayman** [comment]
I've never had luck with cross-refs.  The BST we have is basically the ACMs...we might could think about pushing back up to them if we come up with the fix.

**Comment by snapdragoness** [comment]
I took a quick look around at the code; seems the BST is using `\citeN`, which is specified in the CLS. I do not see a quick easy fix; will just work without cross-refs for now.

**Comment by ayman** [comment]
We should address this post CHI16 deadline.
