### ISSUE TITLE
"Add Tags to Document" in Acrobat (v10.1.15) makes document unreadable on iOS 9

### ISSUE THREAD

**Issue by matsch-o0** [sigchi/Document-Formats#54]
"Add Tags to Document" in Acrobat (v10.1.15) makes the resulting PDF document unreadable on iOS 9 (see screenshot of output at bottom)

Steps to reproduce the error:
1. Compile a clean PDF from the proceedings.tex example.
2. "Add Tags to Document" in Acrobat.
3. View on iOS 9 device.
4. Profit!

I don't have an iOS device myself to debug this. The accessible PDF looks fine in iSimulator with iOS 8.2 on my Mac. I know Add Tags introduces an unembedded Times-Roman font. I was able to re-embed the font with Acrobat. Now shows as "TimesNewRoman (Embedded Subset), Type: TrueType (CID)". However, the problem on iOS 9 unfortunately persists.

I don't know if the problems also exists with a .doc file as the source. No iOS device to really debug, as I said.

![sigchi-ios9-](https://cloud.githubusercontent.com/assets/599237/9977452/d33fb1ce-5ed6-11e5-93bf-34b77b03e689.jpg)

**Comment by ayman** [comment]
Can you supply example url?

**Comment by matsch-o0** [comment]
Yes, plenty. Sorry.

Faulty in iOS 9 (Safari and iBooks affected is what I heard.):
- Example from above (just "Add Tags"): http://mkorn.binaervarianz.de/pub/proceedings.pdf
- a different example ("Add Tags" and all other Accessibility Guidelines from CHI 2015): http://mkorn.binaervarianz.de/pub/korn-cscw2016.pdf
- same as above, but with Times-Roman re-embedded as TimesNewRoman: http://mkorn.binaervarianz.de/pub/korn-cscw2016-2.pdf

NOT faulty in iOS 9 (i.e., looking fine):
- not accessbile original: http://mkorn.binaervarianz.de/pub/korn-cscw2016-3.pdf

**Comment by matsch-o0** [comment]
Is anyone with iOS9 able to reproduce the problem? Does it affect other devices too?

**Comment by ayman** [comment]
I'm wondering if this is related to #59 and 7 bit fonts.

**Comment by ayman** [comment]
So the problem went away after we closed #59...or at least I can't replicate it using current iOS and latest Acrobat Pro DC.
