### ISSUE TITLE
Figure placement in Example Word Document

### ISSUE THREAD

**Issue by mporcheron** [sigchi/Document-Formats#57]
The example Word document states that figures and table should be placed at the top or bottom of columns, however, on the very same page both a figure and a table are placed in the middle of a column.

<img width="1392" alt="screen shot 2015-10-11 at 17 25 51" src="https://cloud.githubusercontent.com/assets/844463/10417699/401e5b20-703d-11e5-80a2-7e231b163caf.png">

(I'd make a pull request with a corrected Word document, but I'm not sure how Git manages the merging of docx files).

**Comment by ayman** [comment]
I think it will overwrite and not merge the binary docx.  Give it a shot with the pull request - we'll see how it handles it.

**Comment by jofish** [comment]
I'd suggest re-writing the text to say something like "In general, figures and tables should be placed...". I think of this as a guideline, not a hard-and-fast rule. There are definitely circumstances where this should be optional.

**Comment by ayman** [comment]
We generally state this as 'We recommend ..." feel free to add as needed.
We'll review.
