### ISSUE TITLE
Can't use underscore in \author{}

### ISSUE THREAD

**Issue by anjiro** [sigchi/Document-Formats#59]
Example:

```
\author{%
  \alignauthor{Leave Authors Anonymous\\
    \affaddr{for Submission}\\
    \affaddr{City, Country}\\
    \email{hello\textunderscore friend@myinst.edu}}\\
```

Yields
<img width="234" alt="screen shot 2015-11-11 at 3 13 05 pm" src="https://cloud.githubusercontent.com/assets/386877/11101757/bd5859fe-8886-11e5-8e92-0a2e231aea36.png">

Same results with `\_`.

**Comment by ayman** [comment]
hmm...can you report back what this does:

```
\href{mailto:hello_friend@myinst.edu}{hello\_friend@myinst.edu}
```

will require the `hyperref` package.

**Comment by anjiro** [comment]
Same thing:

![dot](https://cloud.githubusercontent.com/assets/386877/11153262/b676a41c-8a05-11e5-88c2-5e598c1d737b.png)

**Comment by ayman** [comment]
Ok - will investigate...open to suggestions.

**Comment by anjiro** [comment]
I think it might be a font thing. There are a lot of font things going on the .cls file that I don't understand.

**Comment by simonrob** [comment]
I've run into this in the past too. As it only occurs in email addresses, I ended up just using the solution found here (http://tex.stackexchange.com/a/48633):

```
\texttt{\char`_}
```

Until all these little bugs are worked out, maybe there's a case for a "known issues" page for all these templates? (or the GitHub wiki pages).

**Comment by ayman** [comment]
That's (Wiki/Known Issues) a neat idea...i'll try to set it up soon. If @anjiro confirms you're solution we can close this issue.

**Comment by anjiro** [comment]
Ok, I poked at this a little more. The issue is in [line 439 of the .cls file](https://github.com/sigchi/Document-Formats/blob/8cf37a232dbfce7088a442e55e161ac825f2259e/LaTeX/sigchi.cls#L439), where we have

``` latex
\newfont{\eaddfnt}{ptmr7t at 12pt}                    % 05-16-2006 atd
```

I think it's due to the use of a 7-bit font; changing the `7` to `8` makes an (escaped) underscore work properly. I don't know what (if any) implications there are to doing this. Changing all of the `7t`s to `8t` causes no issues with my modern install of MacTeX.

**Comment by simonrob** [comment]
Nice find! No problems here either when changing all 7-bit fonts in that section to 8-bit.

As an aside, this also fixes a related issue where accented characters (e.g., àéîö etc) didn't work in author names. Probably well worth making this change.

**Comment by ayman** [comment]
Wow. Thanks everyone.  So I dug back into the standard ACM template and found the 8-bit fonts were added in 2006. 

``` tex
% *********************************************
%  -- End of block A --
%
%
% -- Start of block B -- UPDATED FONT NAMES
% *********************************************
% Gerry Murray 11/30/2006
% *********************************************
\ifnum\ACM@basesize=9\relax
\newfont{\secfnt}{ptmb8t at 12pt}
\newfont{\secit}{ptmbi8t at 12pt}    %13 Jan 00 gkmt
...
```

So I think we should take this merge too.

**Comment by ayman** [comment]
@anjiro do you have a pull-request for me here?

**Comment by anjiro** [comment]
No, because I'm not familiar enough with Metafont to know how changing from
7- to 8-bit fonts might affect things. I was hoping you knew!

**Comment by ayman** [comment]
Nope...but here's the whole block from the [ACM template](http://www.acm.org/publications/article-templates/proceedings-template.html):

``` tex
\ifnum\ACM@basesize=9\relax
\newfont{\secfnt}{ptmb8t at 12pt}
\newfont{\secit}{ptmbi8t at 12pt}    %13 Jan 00 gkmt
\newfont{\subsecfnt}{ptmri8t at 11pt}
\newfont{\subsecit}{ptmbi8t at 11pt}  % 
\newfont{\ttlfnt}{phvb8t at 18pt}
\newfont{\ttlit}{phvbo8t at 18pt}    % GM 2/4/2000
\newfont{\subttlfnt}{phvr8t at 14pt}
\newfont{\subttlit}{phvro8t at 14pt} % GM 2/4/2000
\newfont{\subttlbf}{phvb8t at 14pt}  % 13 Jan 00 gkmt
\newfont{\aufnt}{phvr8t at 12pt}
\newfont{\auit}{phvro8t at 12pt}     % GM 2/4/2000
\newfont{\affaddr}{phvr8t at 10pt}
\newfont{\affaddrit}{phvro8t at 10pt} % GM 2/4/2000
\newfont{\eaddfnt}{phvr8t at 12pt}
\newfont{\ixpt}{ptmr8t at 9pt}
\newfont{\confname}{ptmri8t at 8pt}
\newfont{\crnotice}{ptmr8t at 8pt}
\newfont{\ninept}{ptmr8t at 9pt}
\fi
\ifnum\ACM@basesize=10\relax
\newfont{\secfnt}{ptmb8t at 13pt}
\newfont{\secit}{ptmbi8t at 13pt}    %13 Jan 00 gkmt
\newfont{\subsecfnt}{ptmri8t at 12pt}
\newfont{\subsecit}{ptmbi8t at 12pt}  % 
\newfont{\ttlfnt}{phvb8t at 20pt}
\newfont{\ttlit}{phvbo8t at 20pt}    % GM 2/4/2000
\newfont{\subttlfnt}{phvr8t at 15pt}
\newfont{\subttlit}{phvro8t at 15pt} % GM 2/4/2000
\newfont{\subttlbf}{phvb8t at 15pt}  % 13 Jan 00 gkmt
\newfont{\aufnt}{phvr8t at 12pt}
\newfont{\auit}{phvro8t at 12pt}     % GM 2/4/2000
\newfont{\affaddr}{phvr8t at 11pt}
\newfont{\affaddrit}{phvro8t at 11pt} % GM 2/4/2000
\newfont{\eaddfnt}{phvr8t at 12pt}
\newfont{\ixpt}{ptmr8t at 10pt}
\newfont{\confname}{ptmri8t at 9pt}
\newfont{\crnotice}{ptmr8t at 9pt}
\newfont{\ninept}{ptmr8t at 10pt}
\fi
```

So it might just be changing 7s to 8s.
