### ISSUE TITLE
EA template: Text is not justified

### ISSUE THREAD

**Issue by luileito** [sigchi/Document-Formats#61]
The template is using `\RaggedRight{}` _together with_ hyphenation, which looks weird:
![raggedright hyphen](https://cloud.githubusercontent.com/assets/1146339/11438150/4987a970-94f3-11e5-8e97-a33ca377e902.png)

On the other hand, the `ragged2e` package provides the `\justify` command, but it breaks the template.

Just to let you know.

**Comment by ayman** [comment]
I dont mind hyphen and ragged right...but am unsure what the official answer is, maybe @jofish can chime in.  We could turn off hyphenation by default and leave it for the author to turn back in if they want, but I'm pretty sure the template should not be justified.

**Comment by jofish** [comment]
Looking back, historically the ExtAbs template has had hyphenation turned off. 

I don't have a strong opinion on this one, but the easiest solution might be just turning hyphenation off in the Latex ExtAbs template.
