### ISSUE TITLE
Dead Link, PDF check at Sheridan

### ISSUE THREAD

**Issue by natpoor** [sigchi/Document-Formats#63]
In the extended abstract file, this link for checking your PDF gets a 404:
http://www.sheridanprinting.com/typedept/ACM-distilling-settings.htm 

(I really hope I don't have some outdated version of the file....)

**Comment by ayman** [comment]
Thanks. Seems the link moved to http://www.sheridanprinting.com/sigchi/ACM-SIG-distilling-settings.htm

**Comment by chrislong** [comment]
Please reopen this issue. Both of these links are dead.

**Comment by ayman** [comment]
The links move around at Sheridan all the time. The new ACM TAPS process resolves all that nonsense from the vendor.
