### ISSUE TITLE
Umlaute (äöü) in author names do not work

### ISSUE THREAD

**Issue by alexsee** [sigchi/Document-Formats#67]
Umlaute like öäü in author names are not rendered in the final pdf (even with activated utf-8). 
Also `\"a` markup is not working.

**Comment by streuselcake** [comment]
See also: Issue #46. I did not reopen my question to make sure I am not the only one facing the problem (even though I tried different editors, including sharelatex).

Here is an example:
...

  \alignauthor{Author 1\
    \affaddr{University of Münster}\
    \affaddr{M{\"u}nster, Germany}\
    \email{author@uni-muenster.de}}\
