### ISSUE TITLE
Template LaTex and Word are not the same

### ISSUE THREAD

**Issue by mendeldesign** [sigchi/Document-Formats#68]
I noticed that the LaTex template for extended abstracts are not the same as the word template. Please find attached the first pages of both pdf outputs, (created on a mac). Notice the difference in font type and the line above the copyright block. When making proceedings for a conference I am confronted with this, because I do not want to ask people to redo their LaTex paper in a Word template, but now I am not able to make consistent proceedings.
![ae 2016 left_latex right_word](https://cloud.githubusercontent.com/assets/831082/12110534/68584608-b38d-11e5-8d21-5ef01142e154.png)

**Comment by ayman** [comment]
Thanks for this.  I was looking into it and I'm not sure if there's much to do here.  Kerning and leading between the two will never be exact. However, we can and should check and see if the hline needs to be at the copyright block or not. @jofish might have the answer here...assigning to him for now.

**Comment by simonrob** [comment]
To get the same fonts as the word version, and much closer formatting (at least for me on OS X), I use XeLaTeX to compile the document, and replace the single fontenc import with the following:

```
\usepackage[T1]{fontenc}
\usepackage{ifxetex}
\ifxetex
    \usepackage{xltxtra}
    \defaultfontfeatures{Scale=MatchLowercase}
    \setmainfont[Mapping=tex-text,Scale=0.8]{Verdana}
    \setsansfont[Mapping=tex-text,Scale=0.9]{Verdana}
    \setmonofont{Monaco}
\else
    \usepackage[utf8]{inputenc}
\fi
```

Happy to make a pull request if this approach also works for others.

**Comment by mendeldesign** [comment]
I am on Texpad for Mac, and the above solution does not create the right style unfortunately.

**Comment by simonrob** [comment]
Weird - make sure you have the Verdana font installed, and that you are definitely using XeLaTeX to compile the document (normal LaTeX will _not_ work)

**Comment by mendeldesign** [comment]
Texpad also compiles using XeLaTex. It works, after I also removed the line
 `\usepackage[scaled=.92]{helvet} % for proper fonts`

Are there many compilers that would not compile correctly? I ask because there are many authors that need instructions.

And there is still the issue with the line above the copyright strip.

**Comment by hci-yeo** [comment]
I also noticed that the template for word and latex is quite different, not only for extended abstract but for paper/note too.
1 obvious difference is the spacing after figure's caption.
In latex the spacing is so large it looks so absurd.
But in word format the space is very small.
For a paper with several figures, so much spaces are lost!
![latex](https://cloud.githubusercontent.com/assets/9024471/12125277/72c1f8c8-b3e2-11e5-82ab-133b776da387.PNG)

Source (pre-rendered PDF examples from this github):
https://github.com/sigchi/Document-Formats/blob/master/Examples/LaTeX%20SIGCHI%20Proceedings%20Format.pdf
https://github.com/sigchi/Document-Formats/blob/master/Examples/Word%20SIGCHI%20Proceedings%20Format.pdf

**Comment by ayman** [comment]
@tcboy88 I think you're overlooking the fact that these are two different typesetting systems...there will be some variance.  LaTeX will be a bit more elastic in it's spacing as it tries to flow and balance the page (imho) better than word does.  If you believe the padding is just too generous, it can be corrected but that's a separate argument (and should be a new issue).

**Comment by hci-yeo** [comment]
@ayman I understand that there will be some variance.
Let's say that I have many figures, it seems like word template will allow me to fit more content?
Do I need to trial and error with both template and choose the one that fits more content?

**Comment by ayman** [comment]
@tcboy88 I agree...we can tighten the template. So if we were to roll into this issue it would be: 1) address line in copyright bloc and 2) tighten padding on floats.

**Comment by mendeldesign** [comment]
I agree with solving the padding, also for items in a (numbered) list.
My concern to start with is that we offer authors both options, but with the ultimate goal to put papers generated by the two different templates together in the proceedings. It feels strange to offer templates that do not generate the same output, because fro me that was the point of providing templates in the first place. Some variance is acceptable, but it should appear to be almost identical. So another option would be to change the word template to better match the LaTex version, but that might start an academic riot.

**Comment by ayman** [comment]
@mjbroekhuijsen I think its less critical for the EA...we spent more time with the archival format doing the matching.

**Comment by mendeldesign** [comment]
@ayman Agreed.

**Comment by ayman** [comment]
I think the padding on the latex still needs addressing...

**Comment by joemarshall** [comment]
Did anything happen with this - the padding on figures is still massive  in the current version unless I'm doing something wrong?

**Comment by ayman** [comment]
I couldn't find a clean solution. Likely it's a no-fix as this version is in sunset anyhow.
