### ISSUE TITLE
Difficult to add authors with different affiliations

### ISSUE THREAD

**Issue by frankbentley** [sigchi/Document-Formats#69]
Superscripts are currently not allowed in the author name or affiliation fields.  There should be a way to add multiple sets of authors who share affiliations (e.g. Authors 1 and 3 are from Institution 1 and Authors 2 and 4 are from Institution 2)

**Comment by ayman** [comment]
This should be pretty easy. I think this will take:
1. A small bit of code to support it.
2. An example in the Wiki to demonstrate it.

**Comment by ayman** [comment]
Put a howto on the [wiki](https://github.com/sigchi/Document-Formats/wiki) if you like.
