### ISSUE TITLE
order blocks of citations automatically in templates

### ISSUE THREAD

**Issue by snapdragoness** [sigchi/Document-Formats#71]
By default, LaTeX will put citations in the order the authors specifies (e.g., [3, 1, 2]); I believe it is more readable to have them in numeric order (e.g., [1, 2, 3]). 

Adding `\usepackage{cite}[nocompress]` to the templates will do this automatically.

**Comment by ayman** [comment]
I think this is a good thing, but it asserts an implicit style (and also won't bulk `[1–4, 7]`).  I think this falls under 'tips and tricks'.  Is the wiki editable by you?  Might be nice to start a section there with stuff like this.

**Comment by snapdragoness** [comment]
Wiki edits all done to reflect this.
