### ISSUE TITLE
Abstracts longer than 9 lines causes a fatal error in EA

### ISSUE THREAD

**Issue by redfood** [sigchi/Document-Formats#73]
When I try to make my abstract longer than 9 lines (approximately 80 words) I get a fatal error while generating a PDF.  I think this is the only relevant error msg:

`./whorl-extended-abstract.tex:407: pdfTeX error (ext4): \pdfendlink ended up in
 different nesting level than \pdfstartlink.
\AtBegShi@Output ...ipout \box \AtBeginShipoutBox 
                                                  \fi \fi 
l.407 \end{document}`

Am I missing something obvious?  Is this a problem with the template or si something up with my LaTeX install?  Any suggestions? 

Thanks.

**Comment by ayman** [comment]
I've had them longer (like 14 lines). Can you share an example?

**Comment by thecoldviews** [comment]
@redfood did you find a work around for this? I am facing the same issue.

**Comment by alialkhatib** [comment]
Can you provide a minimal working example? I made an extended abstract with some dummy text (see [here](https://gist.github.com/alialkhatib/f8935403de7dbfca982587b34e01139d)) which generates 113 words (just barely reaches into 11 lines), and it seems okay (I get a warning about `balance{}` being called in the wrong place, but I always seem to get that 🙄) .

**Comment by thecoldviews** [comment]
I figured it's a problem with the sharelatex compiler. Here is the file - [`link`](https://gist.github.com/jokereactive/02dac35ff84d5d172912d849118c5ce9). 
The Error - 

<img width="419" alt="sharelatex" src="https://user-images.githubusercontent.com/5019716/26903761-5fbeb0fa-4bfc-11e7-94e8-c50923d9626c.png">

Tried the same file in overleaf, worked fine. 

PS: Sorry for the brief comment and delayed response, was chasing a deadline.

**Comment by debapratimsaha** [comment]
@alialkhatib @jokereactive  I'm facing the same problem with TeXmaker. Did anyone figure out what's the root cause? 

Update: I commented out everything below the _abstract_ section and it worked, there is no restriction on the number of lines! I think it might be an issue with other sections of the document. Though it doesn't solve the problem, but it gets the work done.
