### ISSUE TITLE
handling diacritical marks in URLs

### ISSUE THREAD

**Issue by snapdragoness** [sigchi/Document-Formats#77]
What is the appropriate way to handle diacritical marks in URLs for the template (more generally is how we handle unicode characters)? Do they need to be URL encoded, or should they appear as normal (if the former, then we probably should note this somewhere, if latter, the template needs an update)?

Specific example: 

I am trying to cite the url:

`http://bulbapedia.bulbagarden.net/w/index.php?title=Pokémon_data_structure_in_Generation_IV&oldid=2049032`

When it appears in the references, the `é` shows up as `{é}` (which is not a website). I can URL-encode instead, and it will typeset correctly (though it will be a bit ugly). A side issue here is that the URL seems to have been typeset into three separate clickable links (one per wrapped line), none of which actually work.

**Comment by ayman** [comment]
Wow - where do you find these edge cases?  :-) In your BibTeX are you using the `\url{...}` command to wrap it?  Have you tried using `\href{<my_url>}{<description>}`.  So:

```
\href{http://bulbapedia.bulbagarden.net/w/index.php?title=Pok%C3%A9mon_data_structure_in_Generation_IV&oldid=2049032}{http://bulbapedia.bulbagarden.net/w/index.php?title=Pokémon_data_structure_in_Generation_IV&oldid=2049032}
```

Just a thought.

**Comment by snapdragoness** [comment]
I like to live on the edge [cases].

For now, at least, going with wrapping in \url with escaped URL-encoding. It displays this way and the link works (though a little ugly). For the record, in my first post, I was using `\url`, but with the unicode characters.

With enough escaping, I was able to use the `\href` method, but it did not wrap and the URL was in the wrong font / color. (I also tried putting a `\url` inside the `\href`, but that led to an out of memory error, so I assume something catastrophic.) 

Final bib entry and resulting reference attached.

`@misc{Bulbapedia-community:2014aa,
    Author = {{Bulbapedia community}},
    Date-Added = {2015-12-15 19:53:03 +0000},
    Date-Modified = {2016-02-25 22:15:00 +0000},
    Month = {January},
    Note = {\url{http://bulbapedia.bulbagarden.net/w/index.php?title=Pok\%C3\%A9mon\_data\_structure\_in\_Generation\_IV\&oldid=2049032}},
    Title = {Pok{\'e}mon data structure in {Generation IV}},
    Year = {2014}}`

![screen shot 2016-02-25 at 3 19 52 pm](https://cloud.githubusercontent.com/assets/3452924/13336475/53485a6e-dbd3-11e5-89d9-88e387e9f81a.png)

**Comment by ayman** [comment]
Curious, can you just use the UTF-8 text link like `http://bulbapedia.bulbagarden.net/w/index.php?title=Pokémon\_data\_structure\_in\_Generation\_IV\&oldid=2049032` - the font encoding should work with the way the class files are set up.

**Comment by snapdragoness** [comment]
It does appear to mostly work that way. When it typesets, there are additional curly braces, but if you paste the resulting URL to a browser it works (and the curly braces stay):

http://bulbapedia.bulbagarden.net/w/index.php?title=Pok{é}mon_data_structure_in_Generation_IV&oldid=2049032
