### ISSUE TITLE
multi-line section headers have extra space in LaTeX format

### ISSUE THREAD

**Issue by snapdragoness** [sigchi/Document-Formats#78]
When a section header has to be line-wrapped in the LaTeX format, there is extra spacing between the lines. See piece of screen shot:

![screen shot 2016-03-22 at 11 30 53 am](https://cloud.githubusercontent.com/assets/3452924/13961299/a4d3c6ae-f021-11e5-8aa2-5a8b8cf9ec64.png)

This does not appear to be true in the Word format. 

![screen shot 2016-03-22 at 11 31 08 am](https://cloud.githubusercontent.com/assets/3452924/13961294/a0457c72-f021-11e5-96e7-6bf68a9a8688.png)

**Comment by ayman** [comment]
Ok...if someone knows where that is set, we can maybe tighten it a bit, but imho word is too tight.

**Comment by snapdragoness** [comment]
Lines 1116–1133 specify an additional baselineskip for multi-line headers. Not sure how tight to make it; 10pt looks better than the currently set 14pt in my environment (but if the format gods think that's too tight, I am good with a looser setting). 

![screen shot 2016-03-22 at 1 56 37 pm](https://cloud.githubusercontent.com/assets/3452924/13965955/fe1c056e-f035-11e5-9772-d2bd94a88fb5.png)

**Comment by ayman** [comment]
I think a comparison to the ACM standard conf template is in order...but if i were to guess, i'd say moving it to 12pt is likely a safe squish.
