### ISSUE TITLE
Enable use of CCS 2012 auto-generated latex

### ISSUE THREAD

**Issue by jofish** [sigchi/Document-Formats#8]
http://dl.acm.org/ccs_flat.cfm

http://dl.acm.org/ccs_flat.cfm#10003120

``` latex
\begin{CCSXML}
<ccs2012>
<concept>
<concept_id>10003120.10003121.10003124.10010868</concept_id>
<concept_desc>Human-centered computing~Web-based interaction</concept_desc>
<concept_significance>500</concept_significance>
</concept>
<concept>
<concept_id>10003120.10003121.10003124.10010862</concept_id>
<concept_desc>Human-centered computing~Command line interfaces</concept_desc>
<concept_significance>100</concept_significance>
</concept>
<concept>
<concept_id>10010147.10010371.10010387.10010866</concept_id>
<concept_desc>Computing methodologies~Virtual reality</concept_desc>
<concept_significance>300</concept_significance>
</concept>
</ccs2012>
\end{CCSXML}

\ccsdesc[500]{Human-centered computing~Web-based interaction}
\ccsdesc[100]{Human-centered computing~Command line interfaces}
\ccsdesc[300]{Computing methodologies~Virtual reality}
```

**Comment by ayman** [comment]
A related link that also asks how?

http://academia.stackexchange.com/questions/15252/is-the-new-acm-2012-taxonomy-usable-in-use

**Comment by ayman** [comment]
This is a rather large change as it says to swap the current classification scheme for the newer 2012.  This has implications for the word template as well as per [their instructions](http://www.acm.org/publications/article-templates/CCS-HOWTO-v6-12Jan2015.pdf). 

Here's a comparison of the older and newer classifications:

![image](https://cloud.githubusercontent.com/assets/1846/6765591/751da8ba-cfa4-11e4-9230-fef2ee9c66b3.png)
