### ISSUE TITLE
How should I refer to a section

### ISSUE THREAD

**Issue by vinhqdang** [sigchi/Document-Formats#80]
Hello

Usually I use `\label` and `\ref` to refer to a section.

Example:

```
In Section \ref{sec:1} we do ...

...

\section{ABCDEF} \label{sec:1}
```

However, it seems that SIGCHI format eliminate the section numbers, and the warning will be generated. What should I do to cross refer to a section in the document?

Thanks

**Comment by luileito** [comment]
You could use hyperref's `\nameref` command to crossref a Section name.

**Comment by alialkhatib** [comment]
Seems related to #12; I like the `\nameref` suggestion too; you risk ambiguity (e.g. if you have multiple (sub)sections called "foo" and you say "in section foo..."), but that seems to be the cost of not numbering sections 😛

**Comment by vinhqdang** [comment]
What is the best way to use `\nameref`

For instance, I am writing as (after compilation):

`As we discussed in Section Background Information, .....`

(before, it was `As we discussed in Section 2, ....`).

And, well, there are several duplications in my writing (e.g. subsection names are duplicated). I have to deal with it I guess.

**Comment by luileito** [comment]
@alialkhatib In that case you can define your own `\mynameref` command to print e.g. `Sec.` or `Subsec.` before (sub)section names.

Preamble:

``` tex
\def\sectionautorefname{Sec.}
\def\subsectionautorefname{Subsec.}
\renewcommand*{\thesection}{\null}
\renewcommand*{\thesubsection}{\null}

\newcommand*{\mynameref}[1]{\autoref{#1}\nameref{#1}}
```

Document:

``` tex
\section{Foo}\label{sec:foo}
\subsection{Foo}\label{subsec:foo}

In \mynameref{sec:foo} and \mynameref{subsec:foo} ...
```

Output:

```
In Sec. Foo and Subsec. Foo ...
```

**Comment by ayman** [comment]
This would be nice to put in the [wiki](https://github.com/sigchi/Document-Formats/wiki).

**Comment by mitar** [comment]
Oh, is referencing by name ugly. :-(
