### ISSUE TITLE
Teaser image below title

### ISSUE THREAD

**Issue by joobei** [sigchi/Document-Formats#83]
If I remember correctly there used to be a \teaser command so that one could insert a teaser image below the title. This command appears to not be available in this version (096170b). Is there some workaround for this?

**Comment by simonrob** [comment]
As far as I can remember the `\teaser` command is only from the Extended Abstract version. I do this to get a first page two-column figure in the main template:

```
% before \begin{document} 
\usepackage{cuted}
\usepackage{capt-of}

% before \begin{abstract}
\begin{strip}\centering
\includegraphics[width=\textwidth]{feature-graphic.pdf}
\captionof{figure}{Feature graphic caption.
\label{fig:feature-graphic}}
\end{strip}
```

**Comment by ayman** [comment]
I tend to think this is a how to rather than should be a command.  Feel free to add it to the wiki: https://github.com/sigchi/Document-Formats/wiki/Tips-%26-Tricks

**Comment by simonrob** [comment]
Done
