### ISSUE TITLE
Order of Author and ACM Keywords

### ISSUE THREAD

**Issue by matsch-o0** [sigchi/Document-Formats#85]
Between Word and Latex templates the order of Author and ACM Keywords is reversed. For both templates keywords should be in the same order.

Word has Author Keywords first, ACM second.
Latex has ACM Keywords first, Author second.

The Word-variant seems more widely spread: Author Keywords first, ACM second.

**Comment by ayman** [comment]
LaTeX would be the ACM default afaik.  Got a P/R?
