### ISSUE TITLE
ODT formatted templates

### ISSUE THREAD

**Issue by mrshll1001** [sigchi/Document-Formats#86]
The docx templates are mangled when opened in other office suites such as LibreOffice or OpenOffice, which makes it more difficult to collaborate with those who do use Word and can't use LaTeX.

Having a set of ODT formatted templates would allow use of Libre/Open Office. Is it possible to either have these provided or to provide some "specs" to work towards making my own to contribute back upstream?

**Comment by floe** [comment]
I second this. FWIW, I've had the experience that plain old .doc (Word 97) format is a lot better supported in open-source software, and doesn't miss any features that would be relevant for the template.

**Comment by ayman** [comment]
Aren't the 'specs' written into the doc itself?  I'm happy to host an unsupported set of templates in the `Extras` directory.

**Comment by floe** [comment]
Can someone with a recent version of Word (online version won't work AFAICT) take the current template, save it in Word 97 format and attach that to this issue? I'll see if I can transform that into a sensible ODT template.

**Comment by ayman** [comment]
@floe Attached here. 

[DOC files.zip](https://github.com/sigchi/Document-Formats/files/603771/DOC.files.zip)

**Comment by floe** [comment]
Gave it a quick try, but I have to admit I'm obviously not proficient enough in {Open|Libre}Office to fix all the little issues that popped up. However, the result definitely looks closer to the original than when importing the DOCX versions.

**Comment by mrshll1001** [comment]
This is much better already. Going to spend a few hours on the weekend tweaking.

**Comment by floe** [comment]
For the record, and for others to fiddle around with:
[SIGCHIProceedingsFormat_odt.zip](https://github.com/sigchi/Document-Formats/files/612908/SIGCHIProceedingsFormat_odt.zip)

**Comment by ayman** [comment]
Looked 'ok enough' - maybe put it in the extras directory as it will be unsupported?

**Comment by floe** [comment]
OK, I'll clean it up a little more and send a PR. Note: the EA template was a complete mess, that would probably have to be re-built from scratch as ODT.

**Comment by floe** [comment]
PR (by someone else) is in #102 .
