### ISSUE TITLE
"and others" in author list renders as "and others" instead of "et al."

### ISSUE THREAD

**Issue by reidpr** [sigchi/Document-Formats#87]
`.bib` entry:

```
@inproceedings{achrekar2011,
  title = {Predicting flu trends using {{Twitter}} data},
  doi = {10.1109/INFCOMW.2011.5928903},
  timestamp = {2016-10-11T22:46:50Z},
  booktitle = {Computer {{Communications Workshops}} ({{INFOCOM Workshops}}))},
  year = {2011},
  author = {Achrekar, Harshavardhan and others}
}
```

Actual behavior:

<img width="388" alt="screen shot 2016-10-12 at 10 24 34 am" src="https://cloud.githubusercontent.com/assets/1682574/19318471/1daa2d5e-9066-11e6-9adf-599a32bd6523.png">

Expected behavior:

<img width="384" alt="screen shot 2016-10-12 at 10 25 24 am" src="https://cloud.githubusercontent.com/assets/1682574/19318503/39283de6-9066-11e6-9240-bc3b2ff0fcab.png">

Fix available in my fork, reidpr/Document-Formats@d41425c.

**Comment by ayman** [comment]
This is a good fix however we were trying **not** to edit the BST file from the ACM. is the _'and others'_ a common bibtex convention?

**Comment by reidpr** [comment]
It's not a convention. It's the documented way to specify *et al.* with the extra authors not present in the `.bib` file.

I am unclear why you have an issue tracker that you encourage folks to use, if you don't want to fix bugs?

I'll add that I filed several excellent bug reports, and what I got for my troubles was varying degrees of "piss off", so in the future I'll just fix things in my fork and not report them any more.

**Comment by ayman** [comment]
We've been taking (and have taken most all) pull requests. I only explained the rationale for not messing with the ACM bst and would happily take a P/R for this.  I can't pull your fork - you have to send the request. 

> It's not a convention. It's the documented way to specify et al. with the extra authors not present in the .bib file.

explains that this is a bug in their bst and not just a feature you're adding...which is good to understand the issue.
