### ISSUE TITLE
Year appears twice in several citation types

### ISSUE THREAD

**Issue by reidpr** [sigchi/Document-Formats#88]
`.bib` entry:

```
@article{althouse2011,
  title = {Prediction of dengue incidence using search query surveillance},
  volume = {5},
  doi = {10.1371/journal.pntd.0001258},
  timestamp = {2016-04-28T21:56:48Z},
  number = {8},
  urldate = {2013-12-11},
  url = {http://dx.doi.org/10.1371/journal.pntd.0001258},
  journal = {PLOS Neglected Tropical Diseases},
  author = {Althouse, Benjamin M. and Ng, Yih Yng and Cummings, Derek A. T.},
  month = aug,
  year = {2011}
}
```

Actual behavior:

<img width="382" alt="screen shot 2016-10-12 at 10 35 03 am" src="https://cloud.githubusercontent.com/assets/1682574/19318872/907d82f8-9067-11e6-9527-ec442d178d3c.png">

Expected behavior:

<img width="391" alt="screen shot 2016-10-12 at 10 36 58 am" src="https://cloud.githubusercontent.com/assets/1682574/19318930/d3efc82a-9067-11e6-8aaa-47d9b3cf1f3a.png">

I found this in `article` and `misc`; it may be in other reference types as well.

Fix (perhaps partial) available in fork, reidpr/Document-Formats@c3167cd.

**Comment by jofish** [comment]
Nope. This is a wontfix because that's the ACM standard reference format. According to an email I got from Craig Rodkin (who's running the ACM-wide LaTex revision process) on August 31st, this is on a list to fix in 2018 but right now it's staying:

> Regarding Months in journal article references: in the interests of time and money, we’ll keep the spec we now have – it includes the month along with a repeated year. We will add this to a list I will maintain for potential changes in 2018.
