### ISSUE TITLE
Text citation commands in sigchi.cls not working. 

### ISSUE THREAD

**Issue by elisehein** [sigchi/Document-Formats#93]
I've normally used `\textcite{}` from the `biblatex` package to cite authors in-text ("Brandt et al (2008) found..."), but because `biblatex` is not compatible with custom .bst files, this seems not to be an option with the proceedings template, leaving me only with the basic `\cite{}` command that just adds the number of the reference in brackets.

I tried using `natbib`'s `\citet{}` instead, but getting the error `Package natbib Error: Bibliography not compatible with author-year citations.`. 

Does the SIGCHI Proceedings format even allow textual references, or is this simply a technical issue?

**Comment by ayman** [comment]
References are currently numbered not textual. However, being able to just drop the year or authors in is interesting. There are some commands in the `cls` file to do this like `\citeyear` but they dont seem to be working. Marking as bug.

**Comment by elisehein** [comment]
Thanks!

To clarify, I'm not looking to change the core reference format from numbered to something else. But I do believe in-text author citations like "Brandt et al. [1]" are allowed in ACM.

**Comment by ayman** [comment]
Yes, and there's a set of cite commands in the `cls` file that should do that, but I am unable to get them to produce anything aside from the number citation.  Will update title to reflect this. For reference: https://github.com/sigchi/Document-Formats/blob/master/LaTeX/sigchi.cls#L1360-L1369

**Comment by elisehein** [comment]
Same here.

**Comment by DorisxinDU** [comment]
the same problem, did it solve?

**Comment by henrikkorsgaard** [comment]
Any news on this? We desperately need citation features similar to the base ACM LaTeX template (https://www.acm.org/publications/proceedings-template) or natbib, e.g. \citeauthor, \citeyear and perhaps even proper \cite[e.g.][page]{key} support.

**Comment by ayman** [comment]
These templates are in sunset in favor of the newer ACM templates.
