### ISSUE TITLE
Braces in paper header

### ISSUE THREAD

**Issue by henningpohl** [sigchi/Document-Formats#95]
Adding braces to, e.g., combine multiple author emails fails for me. While \\{ and \\} work in the main text, in the header they produce the wrong characters. Here's a minimal example:

```
\documentclass{sigchi}

\usepackage{graphics}
\usepackage[T1]{fontenc}
\usepackage{color}

\begin{document}

\title{Test Title with \{Braces\}}

\numberofauthors{1}
\author{
  \alignauthor Author 1, Author 2\\
    \affaddr{Test Uni}\\
    \email{\{author1, author2\}@test.edu}\\
}

\maketitle

\begin{abstract}
Text in abstract with \{braces\}.
\end{abstract}

\end{document}
```

When I compile this, the title comes out as: Test Title with –Braces˝

**Comment by henningpohl** [comment]
A workaround is to explicitly request the roman font via:
`\textrm{\{}` and `\textrm{\}}`

**Comment by ayman** [comment]
Can you transfer this to the wiki?
