### ISSUE TITLE
\tableofcontents prohibited in sigchi.cls

### ISSUE THREAD

**Issue by elisehein** [sigchi/Document-Formats#97]
The sigchi document class disallows the use of a table of contents:

```
\def\tableofcontents{\@latexerr{\tableofcontents: Tables of contents are not
  allowed in the `acmconf' document style.}\@eha}
```

Rather than producing an error, would it make sense to define a standard `\tableofcontents` (e.g., based on article.cls), and produce a warning instead?

**Comment by ayman** [comment]
I'm not sure I follow why? The ACM format forbids it, so why should the template allow it with a warning?

**Comment by elisehein** [comment]
Agreed. A table of contents looks horrible with this template anyway and makes no sense for the short-ish articles it's meant to serve. In my case, however, our university department has prescribed the sigchi proceedings template for all dissertations (don't ask...). Dissertations obviously span many pages and hugely benefit from a table of contents.

For others needing a table of contents for whatever reason, I found help on StackOverflow:

http://tex.stackexchange.com/questions/346012/define-tableofcontents-in-document-class-that-doesnt-support-it

http://tex.stackexchange.com/questions/346177/unable-to-include-tocloft-package-with-custom-document-class

Surely responsible authors do not need a .tex template to dictate what they should and should not use. Forbidding `\tableofcontents` entirely sounds unnecessarily constraining to me.

**Comment by ayman** [comment]
Ok. I think this falls out of scope for SIGCHI as the template is to make sure no errors happen for articles. Perhaps fork this repo and add edits for your department. If you just comment out those lines at https://github.com/sigchi/Document-Formats/blob/master/LaTeX/sigchi.cls#L598-L599 then it should work.

**Comment by elisehein** [comment]
For others needing this, commenting out the `\tableofcontents` declaration from the .cls will produce an undefined control sequence error. Some solutions pointed out here http://tex.stackexchange.com/questions/346012/define-tableofcontents-in-document-class-that-doesnt-support-it
